spring.kafka.bootstrap-servers=192.168.100.10:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-serializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=ev_central_group

listeners=PLAINTEXT://0.0.0.0:9092
advertised.listeners=PLAINTEXT://192.168.100.10:9092

server.port=${ENGINE_HOST_PORT:8081}       # Default to 8081 if variable not set
spring.application.name=${CHARGER_APP_NAME:cp1000}

eureka.client.service-url.defaultZone=http://192.168.100.50:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true