server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Eureka server advertises itself using its static IP
eureka.instance.hostname=192.168.100.50
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://192.168.100.50:8761/eureka/
server.address=0.0.0.0