version: "3.8"

services:
  ev-driver:
    build:
      context: ./EV_Driver
      dockerfile: dockerfile
    container_name: ev-driver
    ports:
      - "7040:8080"
    image: ev_driver:latest
    restart: unless-stopped
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=192.168.100.10:9092
