version: "3.9"

networks:
  alicante:
    external: true

services:
  # ----------------------------------------
  # Eureka Server
  # ----------------------------------------
  eureka-server:
    image: eclipse-temurin:21-jdk  # <-- Use Java 21 to match your build
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    hostname: eureka-server
    networks:
      alicante:
        ipv4_address: 192.168.100.50
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - SERVER_PORT=8761
   

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8493:8080"

    networks:
      - alicante
