services:
  # --------------------------------------------------------------------
  # Application Services
  # --------------------------------------------------------------------
  ev_central:
    build: ./EV_Central
    container_name: ev-central
    ports:
      - "8081:8080"
      - "5500:5500"
      - "9900:9900" #web port
    environment:
      # Connect to local Kafka on your Mac
      KAFKA_BOOTSTRAP_SERVERS: 192.168.100.10:9092
    networks:
      alicante:
        ipv4_address: 192.168.100.100

  # --------------------------------------------------------------------
  # Database & Admin Tool
  # --------------------------------------------------------------------
  ev_db:
    image: mysql:8
    container_name: ev-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ev_database
      MYSQL_USER: ev_user
      MYSQL_PASSWORD: ev_password
    ports:
      - "3307:3306"
    volumes:
      - ev_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "192.168.100.102", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      alicante:
        ipv4_address: 192.168.100.101  # Static IP for the database - same as central

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ev-phpmyadmin
    ports:
      - "8060:80"
    environment:
      PMA_HOST: ev_db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      ev_db:
        condition: service_healthy
    networks:
      alicante:
        ipv4_address: 192.168.100.102  # Static IP for phpMyAdmin - same as central

# --------------------------------------------------------------------
# Networks and Volumes
# --------------------------------------------------------------------
networks:
  alicante:
    external: true # So this can connect to other Docker Compose projects (like Driver, CP, etc.)

volumes:
  ev_db_data: